### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by tehnar** [tehnar/SPbAU-KOP2#1]
- [x] isInside
- [x] findTangent
- [x] distance(Point, Polygon)
- [x] intersection(Line, Polygon)
- [x] extremePoint(Polygon, direction)
